### ISSUE TITLE
FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by mainmango** [Lacro59/playnite-gameactivity-plugin#130]
Hi,

Receiving the following error when exiting League of Legends.

Thanks.

13-03 17:06:12.234|ERROR|GameActivity#Common:Error on <OnGameStopped>b__0()|D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs|1133
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToUInt64(String value)
   at GameActivity.GameActivity.GetPlayStatePausedTimeInfo(Game game) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs:line 1188
   at GameActivity.GameActivity.<>c__DisplayClass26_0.<OnGameStopped>b__0() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\GameActivity.cs:line 1133

**Comment by Jhanlon95** [comment]
I am also getting this error.
[log file created](https://github.com/Lacro59/playnite-gameactivity-plugin/files/8240976/GameActivity_2022-03-14.zip)

**Comment by BanCrash** [comment]
This issue is already fixed in master.

But I don't know what is causing it, since the PlayState txt should not be empty. Hope the new delay fixes also the playstate being empty when GameActivity reads it. In any case, this issue should not appear any longer.

**Comment by mainmango** [comment]
Is there something we can do to fix the error or do we need to wait for an update or something?

**Comment by BanCrash** [comment]
> Is there something we can do to fix the error or do we need to wait for an update or something?

This won't be fixed until next release, but in the meantime you can disable (no need to uninstall) PlayState and then go to %AppData%\Playnite\ExtensionsData  (or if you want to go manually, it's placed on C:\Users\<User>\AppData\Roaming\Playnite\ExtensionsData) and delete the PlayState.txt file placed inside. After the next update you can enable again PlayState.

BTW, sorry about this issue. I didn't have it on my tests, don't know what could be happening. I didn't include a setting to enable or disable this to ease the code removal in the future when a proper way is added, but turns out that it was a bad idea. I will work on it on Thursday, so at least in case there are more unpleasant surprises there is a way to avoid them.

**Comment by mainmango** [comment]
I deleted the PlayState.txt and also disabled and uninstalled Playstate but the issue still persists. 

Also it seems to have broken my GameActivity as the dates are showing 1980s and no longer capturing my game session times. :(

Appreciate your quick responses though! 

![image](https://user-images.githubusercontent.com/4985901/158310941-ce8fb527-01f9-4a5e-94d8-89011b5cc46d.png)

**Comment by BanCrash** [comment]
> I deleted the PlayState.txt and also disabled and uninstalled Playstate but the issue still persists.
> 
> Also it seems to have broken my GameActivity as the dates are showing 1980s and no longer capturing my game session times. :(
> 
> Appreciate your quick responses though!
> 
> ![image](https://user-images.githubusercontent.com/4985901/158310941-ce8fb527-01f9-4a5e-94d8-89011b5cc46d.png)

Could you check that PlayState.txt didn't get generated again?

**Comment by mainmango** [comment]
Oh weird it did get generated again. Looks like gameactivity is capturing properly now!

Awesome.

**Comment by BanCrash** [comment]
> Oh weird it did get generated again. Looks like gameactivity is capturing properly now!
> 
> Awesome.

Glad to read that, when the next update is released you can install again PlayState and shouldn't be more issues. I can't assure that PlayState.txt will be not empty though, but at least you won't get this error any longer and your activity will get recorded as expected.

**Comment by BanCrash** [comment]
BTW @mainmango , you can manually add your missing entries if you want. All the info you need should be on your extensions.log

**Comment by mainmango** [comment]
Good to know thanks!

**Comment by BanCrash** [comment]
@mainmango @Jhanlon95 new version with the fix is released.

**Comment by mainmango** [comment]
Closing because issue is resolved. Thanks!
